// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBDTWOzk1vbf0bHT3F3v1fKidgPrFPU3Ew',
    appId: '1:956135836535:web:bf77529bc3ae99b7942f72',
    messagingSenderId: '956135836535',
    projectId: 'vyapar-6eade',
    authDomain: 'vyapar-6eade.firebaseapp.com',
    storageBucket: 'vyapar-6eade.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQMJx9xuOzppE83P7FFzvC1qM4lzGSX4o',
    appId: '1:956135836535:android:181daec19c80caa0942f72',
    messagingSenderId: '956135836535',
    projectId: 'vyapar-6eade',
    storageBucket: 'vyapar-6eade.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeg9aUxOP0f4Y4E8woA9uHzxfCk1pq9Gg',
    appId: '1:956135836535:ios:e584cc34e07897e4942f72',
    messagingSenderId: '956135836535',
    projectId: 'vyapar-6eade',
    storageBucket: 'vyapar-6eade.firebasestorage.app',
    iosBundleId: 'y',
  );
}
